DROP TABLE photo_tag CASCADE;
DROP TABLE member_tag CASCADE;
DROP TABLE tagtype CASCADE;
DROP TABLE member_photo CASCADE;
DROP TABLE tag CASCADE;
DROP TABLE tag_photo CASCADE;
DROP TABLE photo CASCADE;
DROP TABLE member CASCADE;
