DROP TABLE IF EXISTS photoshare.photo_tag CASCADE;
DROP TABLE IF EXISTS photoshare.member_tag CASCADE;
DROP TABLE IF EXISTS photoshare.tagtype CASCADE;
DROP TABLE IF EXISTS photoshare.member_photo CASCADE;
DROP TABLE IF EXISTS photoshare.tag CASCADE;
DROP TABLE IF EXISTS photoshare.tag_photo CASCADE;
DROP TABLE IF EXISTS photoshare.photo CASCADE;
DROP TABLE IF EXISTS photoshare.member CASCADE;
DROP TABLE IF EXISTS photoshare.schema_version CASCADE;
