server:
  port: 8080

spring:
  resources:
    static-locations: classpath:/static/
logging:
  level:
    ROOT: warn
    org.simonscode: debug

graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
